# This is global variable section
http://example.com

token: xyz123
user_id: 123
post_id: abcde12345

--

authorization: :token

GET /home

--


http://example1.com

authorization: BEARER :token
content-type: application/json

PUT /users/:user_id/posts/:post_id

{
    "username": "test",
    "password": "topsecret"
}

--

https://example3.com

content-type: application/x-www-form-urlencoded

POST /users/register

username=test&password=topsecret

--

content-type: application/json

POST /users/register

{
    "username": "test",
    "password": "topsecret"
}
