# This is global variable section
http://example.com

token: xyz123
user_id: 123
post_id: abcde12345

--

authorization: :token

GET /home

--


http://example1.com

authorization: BEARER :token

PUT /users/:user_id/posts/:post_id

{
    "username": "test",
    "password": "topsecret"
}

--

http://example3.com

POST /users/register

{
    "username": "test",
    "password": "topsecret"
}

--

POST /users/register

{
    "username": "test",
    "password": "topsecret"
}
